Turning in assignment
karafulgum/04-surf-and-paddle pull request #1
Opened 2016-09-29 18:40 UTC by karafulgum

2016-10-06 23:21 UTC, rtablada requested changes
The background for the footer should still be full width, just limit the text to the same width as your navbar and main content stuff.

<img width="1680" alt="screen shot 2016-10-06 at 6 16 56 pm" src="https://cloud.githubusercontent.com/assets/2532004/19174018/6e2844f6-8bf1-11e6-8894-a572edd25d97.png">

2016-10-06 23:21 UTC, rtablada commented on app.css
> +  width: 100%;
Try setting `height` to `20rem` and then `object-fit: cover`.

2016-10-06 23:21 UTC, rtablada commented on app.css
> +  width: 100%;
This should fix the white area on the 3rd puppy.

2016-10-07 00:43 UTC, karafulgum commented on app.css
> +  width: 100%;
That worked. Thank you!

2016-12-21 16:28 UTC, merged